language: node_js

node_js:
  - "6"

env:
  global:
    - WORKFLOW_NAME="sync_build_join2"
    - TASK_NAME="build2"
    - ARTIFACT_NAME="echo-vcap.tz"

script:
  - npm test

after_success:
  - npm run version && npm build

before_deploy:
  - mkdir -p tmp && tar -czvf "tmp/$ARTIFACT_NAME" . --exclude "node_modules" --exclude ".git" --exclude "tmp"
  - ./tagrelease.sh
  - export RELEASE_URL="https://github.com/$TRAVIS_REPO_SLUG/releases/download/$GIT_TAG/$ARTIFACT_NAME"

deploy:
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: "tmp/$ARTIFACT_NAME"
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  - git clone https://github.com/uEnsemble/oneshotConductor.git
  - echo "published $RELEASE_URL"
  - cd oneshotConductor && npm install && npm start
